import base64

PWD_HASH_SALT_FOR_GET_HASH = "salt"
PWD_HASH_NAME = 'sha256'
PWD_HASH_SALT = base64.b64decode("salt")
PWD_HASH_ITERATIONS = 100_000
PWD_HASH_ALGORITHM = 'HS256'

TOKEN_EXPIRE_MINUTES = 15
TOKEN_EXPIRE_DAYS = 130
SECRET_KEY = "you-will-never-guess"
